name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 */2 * *"  
  workflow_dispatch:  

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Core configuration
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: Africa/Casablanca
          committer_branch: main
          committer_message: "chore: update GitHub metrics"
        
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: percentage
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          
 
          plugin_repositories: yes
          plugin_repositories_featured: Imadnajam/Imadnajam
          
